"""add qr_codes table

Revision ID: 006_add_qr_codes_table
Revises: 005_add_facility_settings_fields
Create Date: 2025-12-06 10:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '006_add_qr_codes_table'
down_revision: Union[str, None] = '005_add_facility_settings_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # qr_codes テーブル作成（既存チェック付き）
    op.execute("""
        DO $$ BEGIN
            CREATE TABLE qr_codes (
                id SERIAL NOT NULL,
                facility_id INTEGER NOT NULL,
                location VARCHAR(50) NOT NULL,
                custom_location_name VARCHAR(50),
                qr_code_url TEXT NOT NULL,
                qr_code_data TEXT NOT NULL,
                format VARCHAR(10) NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
                PRIMARY KEY (id),
                FOREIGN KEY(facility_id) REFERENCES facilities (id) ON DELETE CASCADE
            );
        EXCEPTION
            WHEN duplicate_table THEN null;
        END $$;
    """)
    
    # インデックス作成（既存チェック付き）
    op.execute("""
        DO $$ BEGIN
            CREATE INDEX ix_qr_codes_id ON qr_codes(id);
        EXCEPTION
            WHEN duplicate_table THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE INDEX ix_qr_codes_facility_id ON qr_codes(facility_id);
        EXCEPTION
            WHEN duplicate_table THEN null;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            CREATE INDEX ix_qr_codes_location ON qr_codes(location);
        EXCEPTION
            WHEN duplicate_table THEN null;
        END $$;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qr_codes_location'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_facility_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_id'), table_name='qr_codes')
    op.drop_table('qr_codes')
    # ### end Alembic commands ###

